# Generated by Django 4.2.1 on 2025-11-18 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('category', models.CharField(choices=[('1', '开发'), ('2', '设计'), ('9', '其他')], default='1', max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注/描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('image_urls', models.TextField(blank=True, default='[]', verbose_name='封面图 URL 列表')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '收藏链接',
                'verbose_name_plural': '收藏链接',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='LinkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='图片URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_links.link', verbose_name='所属链接')),
            ],
            options={
                'verbose_name': '链接图片',
                'verbose_name_plural': '链接图片',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
