# Generated by Django 4.2.1 on 2025-11-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_links', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkImage',
        ),
    ]
